name: game_player_client
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  dio: ^5.4.3+1
  provider: ^6.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  rxdart: ^0.28.0
  pin_code_fields: ^8.0.1
  mobile_scanner: ^5.1.1
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
